apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: knp-d
spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: knp-d
    minReplicas: 1
    maxReplicas: 50
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50