threads: 300  # simulate users
time_on: 60 # time to run attack
time_off: 60 # time to turn off attack
wait_between_requests: 0 # in secs
server_dst: "http://localhost:8080"
logging:
  level: "DEBUG"
  log_name: "ddoser.attack"